### ISSUE TITLE
Fatal Error : Unable to find template "index.html"

### ISSUE THREAD

**Issue by pknadella** [BesrourMS/magazine#1]
Default theme is working fine, but with magazine theme I am getting this error. I am using win10 with XAMPP server stack

```
Fatal error: Uncaught exception 'Twig_Error_Loader' with message 'Unable to find template "index.html" (looked into: C:\xampp\htdocs\pico/themes/magazine).' in C:\xampp\htdocs\pico\vendor\twig\twig\lib\Twig\Loader\Filesystem.php:215 Stack trace: #0 C:\xampp\htdocs\pico\vendor\twig\twig\lib\Twig\Loader\Filesystem.php(139): Twig_Loader_Filesystem->findTemplate('index.html') #1 C:\xampp\htdocs\pico\vendor\twig\twig\lib\Twig\Environment.php(312): Twig_Loader_Filesystem->getCacheKey('index.html') #2 C:\xampp\htdocs\pico\vendor\twig\twig\lib\Twig\Environment.php(378): Twig_Environment->getTemplateClass('index.html', NULL) #3 C:\xampp\htdocs\pico\vendor\twig\twig\lib\Twig\Environment.php(347): Twig_Environment->loadTemplate('index.html') #4 C:\xampp\htdocs\pico\lib\Pico.php(368): Twig_Environment->render('index.html', Array) #5 C:\xampp\htdocs\pico\index.php(20): Pico->run() #6 {main} thrown in C:\xampp\htdocs\pico\vendor\twig\twig\lib\Twig\Loader\Filesystem.php on line 215
```

**Comment by BesrourMS** [comment]
Please check the installation of pico_categories_page & pico_search,

**Comment by pknadella** [comment]
Thanks for the swift reply.

are those two plugins mandatory? nothing like that has mentioned in the theme installation/description, so skipped those.... ok fine .... after installing those two plugins a few lines of warnings and notices are displayed before the previously mentioned error message. 

```
Notice: Undefined index: q in C:\xampp\htdocs\pico\plugins\Pico-Search\pico_search.php on line 26

Warning: strstr(): Empty needle in C:\xampp\htdocs\pico\plugins\Pico-Search\pico_search.php on line 36

Warning: strstr(): Empty needle in C:\xampp\htdocs\pico\plugins\Pico-Search\pico_search.php on line 37

Warning: strstr(): Empty needle in C:\xampp\htdocs\pico\plugins\Pico-Search\pico_search.php on line 41

Warning: strstr(): Empty needle in C:\xampp\htdocs\pico\plugins\Pico-Search\pico_search.php on line 42

Warning: strstr(): Empty needle in C:\xampp\htdocs\pico\plugins\Pico-Search\pico_search.php on line 36

Warning: strstr(): Empty needle in C:\xampp\htdocs\pico\plugins\Pico-Search\pico_search.php on line 37

Warning: strstr(): Empty needle in C:\xampp\htdocs\pico\plugins\Pico-Search\pico_search.php on line 41

Warning: strstr(): Empty needle in C:\xampp\htdocs\pico\plugins\Pico-Search\pico_search.php on line 42

Warning: strstr(): Empty needle in C:\xampp\htdocs\pico\plugins\Pico-Search\pico_search.php on line 36

Warning: strstr(): Empty needle in C:\xampp\htdocs\pico\plugins\Pico-Search\pico_search.php on line 37

Warning: strstr(): Empty needle in C:\xampp\htdocs\pico\plugins\Pico-Search\pico_search.php on line 41

Warning: strstr(): Empty needle in C:\xampp\htdocs\pico\plugins\Pico-Search\pico_search.php on line 42

Notice: Undefined index: search_results in C:\xampp\htdocs\pico\plugins\Pico-Search\pico_search.php on line 55

Notice: Undefined index: q in C:\xampp\htdocs\pico\plugins\Pico-Search\pico_search.php on line 56
```
